# CI/CD Workflow för MyWebApp

name: Deploy MyWebApp to Azure

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Check out this repo
      uses: actions/checkout@v4

    - name: Rensa .NET-cache
      run: dotnet nuget locals all --clear

    - name: Restore dependencies (NuGet)
      run: dotnet restore

    - name: Build and publish MyWebApp
      run: |
        dotnet build --no-restore
        dotnet publish -c Release -o ./publish        

    - name: Upload app artifacts to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: app-artifacts
        path: ./publish
